package nz.ac.wgtn.shadedetector.jcompile.oracles;

import org.apache.commons.lang3.tuple.Pair;
import java.io.IOException;
import java.net.URISyntaxException;
import java.nio.file.Path;
import java.util.Arrays;
import java.util.List;
import java.util.stream.Stream;

/**
 * Construct a negative oracle for classes, i.e. sets of classes that originate from different but similar source code (adjacent versions),
 * generated by the same compiler.
 * @author jens dietrich
 */
public class AdjacentVersionSameArtifactAndCompilerClassOracle extends AbstractClassOracle {

    public AdjacentVersionSameArtifactAndCompilerClassOracle(boolean ignorePackageInfo, boolean ignoreAnonymousInnerClasses) {
        super(ignorePackageInfo, ignoreAnonymousInnerClasses);
    }

    public AdjacentVersionSameArtifactAndCompilerClassOracle() {
        super(true,true);
    }

    @Override
    public List<Pair<ZipPath, ZipPath>> build(Path jarFolder) throws IOException, URISyntaxException {

        List<Pair<Path,Path>> jarOracle = new AdjacentVersionSameArtifactAndCompilerJarOracle().build(jarFolder);
        return buildFromJarPairs(jarOracle);
    }

    //    // for testing TODO: remove
    public static void main (String[] args) throws IOException, URISyntaxException {
        Path jarFolder = Path.of(args[0]);
        List<Pair<ZipPath, ZipPath>> oracle = new AdjacentVersionSameArtifactAndCompilerClassOracle().build(jarFolder);
        System.out.println(String.join("\t", Arrays.asList(
                "container1",
                "container2",
                "class1",
                "class2",
                "compiler_name",
                "compiler_major_version",
                "compiler_minor_version",
                "compiler_patch_version",
                "compiler_extra_config",
                "generated_by_1",
                "generated_by_2",
                "bytecode_jep181_1",
                "bytecode_jep181_2",
                "bytecode_jep280_1",
                "bytecode_jep280_2",
                "scope_1",
                "scope_2",
                "n_anon_inner_classes_1",
                "n_anon_inner_classes_2"
        )));
        for (Pair<ZipPath, ZipPath> paths : oracle) {
            System.out.println(String.join("\t", Stream.of(
                    paths.getLeft().outerPath(),
                    paths.getRight().outerPath(),
                    paths.getLeft().innerPath(),
                    paths.getRight().innerPath(),
                    paths.getLeft().compilerName(),
                    paths.getLeft().compilerMajorVersion(),
                    paths.getLeft().compilerMinorVersion(),
                    paths.getLeft().compilerPatchVersion(),
                    paths.getLeft().compilerExtraConfiguration(),
                    paths.getLeft().generatedBy(),
                    paths.getRight().generatedBy(),
                    paths.getLeft().bytecodeFeatures().contains("JEP181"),
                    paths.getRight().bytecodeFeatures().contains("JEP181"),
                    paths.getLeft().bytecodeFeatures().contains("JEP280"),
                    paths.getRight().bytecodeFeatures().contains("JEP280"),
                    paths.getLeft().scope(),
                    paths.getRight().scope(),
                    paths.getLeft().allInnerPaths().size() - 1,
                    paths.getRight().allInnerPaths().size() - 1)
                .map(Utils::hyphenateEmpty).toList()));
        }
    }

}
